export const LOGIN                      = 'login';
export const LOGOUT                     = 'logout';
export const SIGNUP                     = 'signup';
export const CREATE_USER                = 'createUser';
export const SESSION_CHECK              = 'checkSession';
export const UPDATE_ME                  = 'updateMe';
export const DELETE_USER                = 'deleteMe';
export const DEACTIVATE_USER            = 'deactivateMe';
export const CHANGE_PWD                 = 'changePassword';
export const PWD_FORGOTTEN              = 'passwordForgotten';
export const RESET_PWD                  = 'resetPassword';
export const VALIDATE_RESET_TOKEN       = 'validateResetToken';
export const USER_INFO                  = 'userInfo';
export const USERS_LIST                 = 'usersList';
export const TOGGLE_SUSPENSION          = 'toggleSuspension';
export const CHANGE_ROLE                = 'changeRole';
export const ROLES_LIST                 = 'rolesList';
export const VALIDATE_PASSWORD          = 'password/validate';//este es para el reset dentro de my profile
export const VALIDATE_PASSWORD_RESET    = 'passwordReset/validate';//este es para el reset con token
// export const = '';